loader: 'sh'
dataset:
  root: 'data/shanghai'
  batch_size: 32
  num_workers: 0

model:
  num_rnn_layers: 2
  num_input_dim: 2
  num_rnn_units: 256
  num_nodes: 288
  num_extra_embedding: [73, 2]
  n_heads: 16
  ffn_dim: 256
  st_layers: 1
  st_dropout_rate: 0.2
  output_attention: False
  use_curriculum_learning: True
  cl_decay_steps: 200
  use_input: True

train:
  epoch: 200
  load_param: None
  base_lr: 0.0005
  epsilon: 1.0e-8
  weight_decay: 0.0
  steps: [100, 150, 175]
  lr_decay_ratio: 0.1
  min_learning_rate: 1.0e-06
  warm_up: True
  warm_up_ep: 10
  warm_up_lr: 0.0001
  max_grad_norm: 5
  save_every_n_epochs: 50
